[package]
name = "perf_meter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] } 
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"